//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site_de_la_Technique_Informatique.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminJeu
    {
        public AdminJeu()
        {
            this.LogJeu = new HashSet<LogJeu>();
        }
    
        public int IDAdmin { get; set; }
        public string usagerAdmin { get; set; }
        public string hashMotDePasse { get; set; }
    
        public virtual ICollection<LogJeu> LogJeu { get; set; }
    }
}
