//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site_de_la_Technique_Informatique.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultationForum
    {
        public ConsultationForum()
        {
            this.Membre = new HashSet<Membre>();
        }
    
        public int IDConsultationForum { get; set; }
        public string dateConsulte { get; set; }
        public int EnteteForumIDEnteteForum { get; set; }
    
        public virtual EnteteForum EnteteForum { get; set; }
        public virtual ICollection<Membre> Membre { get; set; }
    }
}
