//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site_de_la_Technique_Informatique.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoursJeu
    {
        public int IDCours { get; set; }
        public string nomCours { get; set; }
        public string noCours { get; set; }
        public int noSessionCours { get; set; }
        public string descriptionCours { get; set; }
        public Nullable<int> UtilisateurJeu_ProfesseurIDUtilisateur { get; set; }
    
        public virtual UtilisateurJeu_Professeur UtilisateurJeu_Professeur { get; set; }
    }
}
