//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site_de_la_Technique_Informatique.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeurJeu
    {
        public EmployeurJeu()
        {
            this.OffreEmploiJeu = new HashSet<OffreEmploiJeu>();
            this.LogJeu = new HashSet<LogJeu>();
        }
    
        public int IDEmployeur { get; set; }
        public string nomEmployeur { get; set; }
        public string hashMotDepasse { get; set; }
        public string courriel { get; set; }
        public bool compteActif { get; set; }
        public bool valideCourriel { get; set; }
        public System.DateTime dateInscription { get; set; }
    
        public virtual ICollection<OffreEmploiJeu> OffreEmploiJeu { get; set; }
        public virtual ICollection<LogJeu> LogJeu { get; set; }
    }
}
