//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site_de_la_Technique_Informatique.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnteteForum
    {
        public EnteteForum()
        {
            this.MessageForum = new HashSet<MessageForum>();
            this.ConsultationForum = new HashSet<ConsultationForum>();
        }
    
        public int IDEnteteForum { get; set; }
        public string titreEnteteForum { get; set; }
        public System.DateTime dateEnteteForum { get; set; }
        public int SectionForumIDSectionForum { get; set; }
        public int MembreIDUtilisateur { get; set; }
    
        public virtual SectionForum SectionForum { get; set; }
        public virtual ICollection<MessageForum> MessageForum { get; set; }
        public virtual ICollection<ConsultationForum> ConsultationForum { get; set; }
        public virtual Membre Membre { get; set; }
    }
}
