//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site_de_la_Technique_Informatique.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnteteForumJeu
    {
        public EnteteForumJeu()
        {
            this.ConsultationForumJeu = new HashSet<ConsultationForumJeu>();
            this.MessageForumJeu = new HashSet<MessageForumJeu>();
        }
    
        public int IDEnteteForum { get; set; }
        public string titreEnteteForum { get; set; }
        public System.DateTime dateEnteteForum { get; set; }
        public int SectionForumIDSectionForum { get; set; }
        public int UtilisateurJeuIDUtilisateur { get; set; }
        public int SectionForumJeuIDSectionForum { get; set; }
    
        public virtual UtilisateurJeu UtilisateurJeu { get; set; }
        public virtual ICollection<ConsultationForumJeu> ConsultationForumJeu { get; set; }
        public virtual ICollection<MessageForumJeu> MessageForumJeu { get; set; }
        public virtual SectionForumJeu SectionForumJeu { get; set; }
    }
}
