//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site_de_la_Technique_Informatique.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LeModelTIContainer : DbContext
    {
        public LeModelTIContainer()
            : base("name=LeModelTIContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DateEvenementVerTIC> DateEvenementVerTICSet { get; set; }
        public DbSet<VerTIC> VerTICSet { get; set; }
        public DbSet<Log> LogSet { get; set; }
        public DbSet<Utilisateur> UtilisateurSet { get; set; }
        public DbSet<OffreEmploi> OffreEmploiSet { get; set; }
        public DbSet<Ville> VilleSet { get; set; }
        public DbSet<ConsultationForum> ConsultationForumSet { get; set; }
        public DbSet<Cours> CoursSet { get; set; }
        public DbSet<Evenement> EvenementSet { get; set; }
        public DbSet<ParutionMedia> ParutionMediaSet { get; set; }
        public DbSet<FAQ> FAQSet { get; set; }
        public DbSet<Nouvelle> NouvelleSet { get; set; }
        public DbSet<SectionForum> SectionForumSet { get; set; }
        public DbSet<EnteteForum> EnteteForumSet { get; set; }
        public DbSet<MessageForum> MessageForumSet { get; set; }
    }
}
