//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site_de_la_Technique_Informatique.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogJeu
    {
        public int IDLog { get; set; }
        public System.DateTime dateLog { get; set; }
        public string actionLog { get; set; }
        public Nullable<int> ProfesseurIDProfesseur { get; set; }
        public Nullable<int> EtudiantIDEtudiant { get; set; }
        public Nullable<int> AdminIDAdmin { get; set; }
        public int UtilisateurIDUtilisateur { get; set; }
    
        public virtual AdminJeu AdminJeu { get; set; }
        public virtual UtilisateurJeu UtilisateurJeu { get; set; }
    }
}
