//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site_de_la_Technique_Informatique.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageForum
    {
        public int IDMessageForum { get; set; }
        public string texteMessage { get; set; }
        public System.DateTime dateMessage { get; set; }
        public int EnteteForumIDEnteteForum { get; set; }
        public int MembreIDUtilisateur { get; set; }
    
        public virtual EnteteForum EnteteForum { get; set; }
        public virtual Membre Membre { get; set; }
    }
}
