//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site_de_la_Technique_Informatique.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Professeur : Membre
    {
        public Professeur()
        {
            this.Cours = new HashSet<Cours>();
            this.Evenement = new HashSet<Evenement>();
            this.ParutionMedia = new HashSet<ParutionMedia>();
            this.FAQ = new HashSet<FAQ>();
            this.Nouvelle = new HashSet<Nouvelle>();
        }
    
        public int IDProfesseur { get; set; }
        public string presentation { get; set; }
    
        public virtual ICollection<Cours> Cours { get; set; }
        public virtual ICollection<Evenement> Evenement { get; set; }
        public virtual ICollection<ParutionMedia> ParutionMedia { get; set; }
        public virtual ICollection<FAQ> FAQ { get; set; }
        public virtual ICollection<Nouvelle> Nouvelle { get; set; }
    }
}
