//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site_de_la_Technique_Informatique.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UtilisateurJeu_Professeur
    {
        public UtilisateurJeu_Professeur()
        {
            this.EvenementJeu = new HashSet<EvenementJeu>();
            this.FAQJeu = new HashSet<FAQJeu>();
            this.NouvelleJeu = new HashSet<NouvelleJeu>();
            this.ParutionMediaJeu = new HashSet<ParutionMediaJeu>();
            this.CoursJeu = new HashSet<CoursJeu>();
        }
    
        public int IDProfesseur { get; set; }
        public int IDUtilisateur { get; set; }
    
        public virtual ICollection<EvenementJeu> EvenementJeu { get; set; }
        public virtual ICollection<FAQJeu> FAQJeu { get; set; }
        public virtual ICollection<NouvelleJeu> NouvelleJeu { get; set; }
        public virtual ICollection<ParutionMediaJeu> ParutionMediaJeu { get; set; }
        public virtual UtilisateurJeu UtilisateurJeu { get; set; }
        public virtual ICollection<CoursJeu> CoursJeu { get; set; }
    }
}
