//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site_de_la_Technique_Informatique.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VerTIC
    {
        public int IDVerTIC { get; set; }
        public string descriptionLicence { get; set; }
        public string descriptionLibre { get; set; }
        public string caractéristiquesPortable { get; set; }
        public string autrePortable { get; set; }
    }
}
